version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ctech_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/server/migrations:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/ctech_db
      FRONTEND_ORIGIN: http://localhost:3000
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: